version: "3.7"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=letmein123
    expose:
      - 5432

  redis:
    image: redis:6
    expose:
      - 6379

  web:
    image: debtcollective/membership:local
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:letmein123@postgres/membership_production
      - RAILS_ENV=production
      - SECRET_KEY_BASE=examplekeybase
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - PORT=5000
    ports:
      - "5000:5000"
    links:
      - postgres
      - redis
