:concurrency: 5
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
:schedule:
  find_overdue_subscriptions:
    every: "24h"
    queue: default
    class: FindOverdueSubscriptionsJob
    description: "This job finds all active overdue subscriptions and creates a sidekiq job to charge the subscriber"
