:concurrency: 5
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
:schedule:
  find_due_subscriptions:
    every: "24h"
    queue: default
    class: FindDueSubscriptionsJob
    description: "This job finds all active due subscriptions and creates a sidekiq job to charge the subscriber"
